### PR TITLE
Fix favicon link

### PR DESCRIPTION
**Pull request by jancborchardt**

### CODE REVIEW

**Comment by evalica** [comment]
I have no experience with "apple-touch-icon-precomposed", but just some notes: 
* According to https://mathiasbynens.be/notes/touch-icons the biggest icon should be 192x192, while we provide a 512 × 512 image
* Do we need a touch icon?

**Comment by Xaviju** [comment]
We may want to support some icons for users who want to add a link to their mobile desktops. I don't really like it but it is kind of standard bad practice.
The question for me is: why only for Apple and specifically `apple-touch-icon-precomposed`?

These are all the icons required to support all platforms:
```
<link rel="shortcut icon" href="/favicon/favicon.ico">
<link rel="icon" sizes="16x16 32x32 64x64" href="/favicon/favicon.ico">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32.png">
<link rel="icon" type="image/png" sizes="64x64" href="/favicon/favicon-64.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96.png">
<link rel="icon" type="image/png" sizes="160x160" href="/favicon/favicon-160.png">
<link rel="icon" type="image/png" sizes="192x192" href="/favicon/favicon-192.png">
<link rel="apple-touch-icon" sizes="57x57" href="/favicon/favicon-57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/favicon/favicon-60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/favicon/favicon-72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/favicon/favicon-76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/favicon/favicon-114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/favicon/favicon-120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/favicon/favicon-144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/favicon/favicon-152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/favicon/favicon-180.png">
<link rel="manifest" href="/favicon/manifest.json">
<meta name="msapplication-TileColor" content="#FFFFFF">
<meta name="msapplication-TileImage" content="/favicon/favicon-144.png">
<meta name="msapplication-config" content="/favicon/browserconfig.xml">
<meta name="theme-color" content="#ffffff">
```

In my opinion, I would remove the OS specific favicons and use the standard.

**Comment by Xaviju** [comment]
This article is really interesting about favicons: http://www.jonathantneal.com/blog/understand-the-favicon/ and it has a deep explanation (and links) about it.

The article recommends something like this (but it is worth reading to adapt it):
```
<link rel="apple-touch-icon" href="path/to/touchicon.png">
<link rel="icon" href="path/to/favicon.png">
<!--[if IE]><link rel="shortcut icon" href="path/to/favicon.ico"><![endif]-->
<!-- or, set /favicon.ico for IE10 win -->
<meta name="msapplication-TileColor" content="#D83434">
<meta name="msapplication-TileImage" content="path/to/tileicon.png">
<link rel="apple-touch-icon-precomposed" href="apple-touch-icon-152x152-precomposed.png">
```

**Comment by simonv3** [comment]
Thanks for the links @Xaviju - that seems a bit more manageable than all the different sizes in your previous comment.

**Comment by jancborchardt** [comment]
Ok – let’s improve these further things in a follow-up. The thing is that now the link is simply broken cause of file renaming, which we should fix. :) Enhancements can be made but shouldn’t block a fix.

**Pull request merged**
