### PR TITLE
Create Open-Source-Design-milestones-over-the-years.md

### PR DESCRIPTION
**Pull request by Erioldoesdesign**
The Milestones 'article' I put together!

### CODE REVIEW

**Comment by SaptakS** [comment]
Codewise looks good. Just wondering if it would make more sense to put it in `opensourcedesign.net/milestones` instead of in the `/articles/` link. Because once we add more articles in future, one will really need to search the link to this post. We can keep in both places as well. What do you think?

**Comment by Erioldoesdesign** [comment]
> Codewise looks good. Just wondering if it would make more sense to put it in `opensourcedesign.net/milestones` instead of in the `/articles/` link. Because once we add more articles in future, one will really need to search the link to this post. We can keep in both places as well. What do you think?

Oh good idea! I should submit a PR for that area too then yes?

**Comment by SaptakS** [comment]
> Oh good idea! I should submit a PR for that area too then yes?

I can just add to this PR. Give me few minutes.

**Comment by SaptakS** [comment]
Done! That should do it!

**Review by AnXh3L0 — APPROVED** [review]

**Pull request merged**
