### PR TITLE
Issues #283

### PR DESCRIPTION
**Pull request by aryasoni98**
#283 
Update `index.html` add URL `Supporters , Conferences , Affiliates` sections

### CODE REVIEW

**Comment by aryasoni98** [comment]
Anyone tell me why conflicting files error show me .

**Comment by Erioldoesdesign** [comment]
I'm not sure what's happening here but perhaps @SaptakS is who I would suggest would maybe know (along with a few other folks at the open source design team with FE knowledge) perhaps also @AnXh3L0 ?

**Comment by SaptakS** [comment]
@aryasoni98 Thanks for the PR!!! The PR needed to be based on top of the master branch instead of the main branch. I fixed that. :) 
Also, the ImgBot PR was created by you for optimizing image sizes? Can you tell me what tool you used for doing that?

**Comment by SaptakS** [comment]
#340 seems to be the new updated PR. Closing this.

**Pull request closed without merging**
