### PR TITLE
Add promotional card and posters

### PR DESCRIPTION
**Pull request by jancborchardt**
I’ll go and print these tomorrow for the Summit. Please check @Incabell @simonv3 @bnvk @belenbarrospena @victoria-bondarchuk @jdittrich @evalica  – we’ll always be able to iterate on these so only see this as a first version. :)

Cards to give out to people, front & back, to be printed as standard small business card, front & back:
card front
card back

Poster which I also used at CSSconf (was designed according to their guidelines) to be printed as A2:
poster

And a special Summit poster, of which we just need a few, mainly for entrances and such:
poster summit

### CODE REVIEW

**Comment by evalica** [comment]
Looks good. Don't make too many with the summit :) and would be great to reuse some of these for FOSDEM. 

I'm not a big fan or card and posters (since I mostly through all of them out) and I prefer stickers :) but I agree they are useful. 

Regarding the card, not really sure why the part "shape the future of security&privacy" is added. I mean, ok, but whatever, not really the case for every design or every organization.

Regarding the Summit poster, you might have some problem printing the background map, but since it's the only graphic we have for the event, let's say ok :)

In general, the proposals are good and thank you for making them :) we definitely were in need of them.

**Comment by jancborchardt** [comment]
> Regarding the card, not really sure why the part "shape the future of security&privacy" is added. I mean, ok, but whatever, not really the case for every design or every organization.

Yeah, true. I mainly wanted to have it be two lines too, and an additional motivations for designers to get involved. Any other ideas?

**Comment by jancborchardt** [comment]
Adjusted the card front side text:
card front

And added the sticker I ordered too (will be cut at the magenta line, of course without the magenta):
sticker opensourcedesign-logo-text-narrow svg

**Comment by simonv3** [comment]
lgtm! thanks for doing this @jancborchardt

**Pull request merged**
