### PR TITLE
Updated index.html 'Become a sponsor' image object

### LINKED ISSUE #285: [CSS]: Button Alignment Main Page
# When we see the main page in responsive view, the alignment of 'Become a sponsor' button is somewhat 'left' to the page

#### Steps to Reproduce:
* Switch to Mobile view
* Scroll to supporter's section
* See the button

#### Screenshot:

Screenshot (487)

#### Additional Context:
If you see this as a genuine issue, I would love to work on it.

### PR DESCRIPTION
**Pull request by sparsh-99**
Fixes #285 

### Styled an image object by reducing its width as it is left-indent a bit.

- Change its width from 150 to 140 to align it in the center.

### CODE REVIEW

**Comment by stygian-96** [comment]
@sparsh-99 I inspected your update in chrome browser by doing the same change that you have made and I found that it has added some extra space over the image!!!

### **Screenshots** -->

**Before changing the width**
Before




**After changing the width**
After

**Comment by sparsh-99** [comment]
@stygian-96 The problem is in mobile view, the left margin is somewhat to the left. I only changed that.

**Comment by stygian-96** [comment]
> @stygian-96 The problem is in mobile view, the left margin is somewhat to the left. I only changed that.

@sparsh-99 I inspected it in the mobile view too and I faced the same issue, it is adding some extra space on the top of the image.

Screenshots -->

Before :
Before-2

After :
After-2

**Comment by sparsh-99** [comment]
_I think you did some mistake, I inspect my changes once again. I think, I good to go for the PR._

**Screenshots:-**

Screenshot (64)


Screenshot (65)

**Review by vinitshahdeo — DISMISSED** [review]

**Comment by jancborchardt** [comment]
I’m a bit confused, as the current https://opensourcedesign.net does already have the width set to 140px – but that actually seems to cause the issue with the misalignment for me?

**Comment by sparsh-99** [comment]
> I’m a bit confused, as the current https://opensourcedesign.net does already have the width set to 140px – but that actually seems to cause the issue with the misalignment for me?

@jancborchardt I think, from June, a few PR's that had been merged since, changed its alignment in mobile view. 
I did my inspection and now '150px' will do the correct alignment.

**Comment by sparsh-99** [comment]
> I’m a bit confused, as the current https://opensourcedesign.net does already have the width set to 140px – but that actually seems to cause the issue with the misalignment for me?

@jancborchardt The width 140px is set to of that <image> tag but what I am proposing is the change in the width of the <object> tag from 150px to 140px which not only aligning the button but also shrinking the extra space between the next paragraph.

1. What you are looking for is this:-

Screenshot (175)

2. and What I am proposing in the index.html file is this:-

Screenshot (176)


**Are you getting the point @jancborchardt ?**

**Comment by Erioldoesdesign** [comment]
Not sure if this needs another look by someone who has better understanding of the changes but the PR is quite old now!

**Comment by Erioldoesdesign** [comment]
Unless someone stops me, I'm going to close this PR without merging - especially since we're doing lots of redesign work on the website

**Review by Arhell — DISMISSED** [review]

**Review by AliReza1083 — COMMENTED** [review]
I reviewed your codes, I find Object tag which I have to go and learn it.
Wish you all the best.

**Comment by Erioldoesdesign** [comment]
@jancborchardt take another look maybe?

**Review by harshsingh32 — APPROVED** [review]

**Review by Felixdiamond — APPROVED** [review]

**Comment by Erioldoesdesign** [comment]
@SaptakS should we merge this or close do you think?

**Comment by SaptakS** [comment]
@Erioldoesdesign this branch has conflicts that need to be resolved. Also, I think I am not happy with the solution. The width of the image is always calculated based on the height (since aspect ratio). Fixing the width works but is finicky and should be fixed as an attribute on our codeside in the `<object>` element with a width attribute equal to the width of the image (i.e. 140px). So might be easier to close this PR and create a new one.

cc @sparsh-99

**Comment by Erioldoesdesign** [comment]
Closing this PR and it can be referenced in a new PR if someone else works on a similar issue

**Pull request closed without merging**
