### PR TITLE
Update resources.md

### PR DESCRIPTION
**Pull request by javierjops**

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Review by ZoranPandovski — APPROVED** [review]

**Comment by javierjops** [comment]
Thanks!

**Comment by javierjops** [comment]
Can you Merge this pull please?

**Comment by jancborchardt** [comment]
This seems a bit much like Shutterstock adware? The text on the page smells of SEO and the photos are pretty generic too.

And then there's this:


I'd say we should revert this? @opensourcedesign/core

**Comment by Erioldoesdesign** [comment]
@jancborchardt yeah I'd be in favour of reverting - there are better photo collections out there done by real humans that I'd sooner promote like:

https://www.flickr.com/photos/mapbox/albums/72157713100349311
https://www.wocintechchat.com/blog/wocintechphotos

Also Pexels is pretty good https://www.pexels.com/

**Pull request merged**
