### PR TITLE
Header fixes

### PR DESCRIPTION
**Pull request by krllb**

### CODE REVIEW

**Comment by jancborchardt** [comment]
@balyasnikovk for any design fix it would be awesome to post a before and after screenshot so it’s easier to review as well. :) (Part of making source code stuff more accessible to designers ;)

**Comment by balyasnikovk** [comment]
@jancborchardt http://i.imgur.com/GuJAoi7.png before and after screenshot :)

**Comment by ei8fdb** [comment]
@balyasnikovk: just so I am not missing something, your proposing the addition of the OpenSourceDesign logo page top left?

**Comment by simonv3** [comment]
@balyasnikovk Thanks so much for the PR. 

Some thoughts:

The original idea was that the logo would only be visible on page scroll, as on the main page the logo and name are already clearly visible front and centre.

New front page:

screenshot 2016-01-19 16 08 06

I think having the logo be always present is a good thing on other pages, but in this branch it's also visible on the front page - would it be possible to do make this not happen on the front page?

What does everyone think?

**Comment by balyasnikovk** [comment]
Hey @simonv3! 
> would it be possible to do make this not happen on the front page?

This is already done in commit f4815259944d7164d2c100d364849429c04f51ac

**Comment by simonv3** [comment]
@balyasnikovk That's the branch I'm looking at and the screenshot is from. What I meant is that it should *not* be showing both logos on the front page without scrolling. 

screenshot 2016-01-19 16 08 06

**Pull request closed without merging**
