### PR TITLE
OSD NYC Meetup Recap

### PR DESCRIPTION
**Pull request by dmichl**
We had a great meeting on November 9th, here's our recap :)

### CODE REVIEW

**Comment by dmichl** [comment]
hey! @jancborchardt could you push this through for me? :) thank you!

**Comment by jancborchardt** [comment]
@dmichl sorry, had vacation last week and wasn’t on the computer mostly. :) Best always @-mention a few people to review.

**Comment by dmichl** [comment]
@jancborchardt no worries! Apologies for always having gone to you :) I hope you had a good vacation. @simonv3 was nice to notice and push them through, I'm still not sure who else have privileges, or should I just ask in chat next time?

**Comment by jancborchardt** [comment]
@dmichl actually everyone who is member of the organization I think. At the very least the owners, who I just added you to also: https://github.com/orgs/opensourcedesign/people?utf8=%E2%9C%93&query=%20role%3Aowner :) 

In general we use pull requests instead of pushing directly so that there’s just another set of eyes looking over it, and also so we have a bit more open process since pull requests – where people get notified – are much more visible than commits. :)

**Pull request merged**
