### PR TITLE
Remove vietnamese charset of Monserrat font

### PR DESCRIPTION
**Pull request by Jc-L**
As mentionned in #227, Vietnamese charset is [to be removed](https://github.com/opensourcedesign/opensourcedesign.github.io/pull/227#issuecomment-472384460 ).

### CODE REVIEW

**Comment by jancborchardt** [comment]
@Jc-L thanks! You can also remove the actual files, right?

**Comment by RDIL** [comment]
@jancborchardt please approve so we can get this merge

**Comment by jancborchardt** [comment]
@RDIL see my previous comment :) It would be good to remove the actual files as well so they don’t stay floating around.

@Jc-L you can also do your work on branches in this main repository instead of using a fork. That way we can collaborate easier and I could do the adjustments on the branch. :)

**Comment by RDIL** [comment]
Ah okay.

**Comment by RDIL** [comment]
I did it to save you time @Jc-L :)

**Comment by Jc-L** [comment]
Thanks for dealing with the file deletion @RDIL 
@jancborchardt : no permissions issue if I work directly in this repo ?

**Comment by RDIL** [comment]
@Jc-L your member status should give you write perms.

**Comment by jancborchardt** [comment]
@RDIL huh, didn’t know you can modify pull requests others did via fork – can I ask how you did that?

**Comment by RDIL** [comment]
If you have write to the branch the PR is targeting then you have write to the branch on the fork also

**Pull request merged**
