### PR TITLE
Copy Richard Barlett's post over to OSD Articles

### PR DESCRIPTION
**Pull request by simonv3**
Let me know what you think @rdbartlett. I didn't embed the videos because I wasn't sure whether there was markdown for that. Maybe someone else knows better?

### CODE REVIEW

**Comment by bnvk** [comment]
@rdbartlett awesome stuff! Thanks for writing this :+1:

**Comment by rdbartlett** [comment]
Thanks @simonv3  and @bnvk! 

I noticed the .gif image is missing, which made me think - would it be good to host the images on osd.net? I'll make a pull request if anyone can advise me on file structure: shall I just plop them into /images and then update the img sources in the blog post?

**Comment by bnvk** [comment]
@rdbartlett @simonv3 yah, I think hositng image media on OSD.net makes a lot of sense... hence the ownership / etc... conversation going on in that other thread!

**Comment by bnvk** [comment]
@rdbartlett out of curiosity, i'm not seeing your post on [our Medium channel](https://medium.com/open-source-design) (or group or whatever they call them), is that intentional or just an oversight?

**Comment by rdbartlett** [comment]
Cool I will make a PR to add the images. 

I'm not sure why the post is not on the front page of the Medium channel (it is there when you click 'More stories' though. I don't think it is intentional. @razetime has admin rights to configure how that front page looks - it might just be set up wrong.

**Comment by jancborchardt** [comment]
Just a small notice – instead of putting »originally written by Richard on Medium« to the article on our blog, can we reverse that and put »originall written by Richard on opensourcedesign.net«? The site should take precendence over a content distribution platform, no?

**Comment by bnvk** [comment]
I definitely agree with @jancborchardt here, I think it's much
better form to be publishing "from OSD.net" and syndicating out
to platforms like Medium which have "follow / subscriber models"

I realize the one problem here might be that Medium offers tools
which make image layouts, etc... which are harder to translate or
implement on our (very minimal) current platform.

On that note, we may want to consider setting up something like
Ghost for the blog. I dunno though, maybe that's overkill.

**Comment by simonv3** [comment]
@bnvk @jancborchardt Let's have that conversation in https://github.com/opensourcedesign/organization/issues/17! There's already some of it there.

**Pull request merged**
