### PR TITLE
Added Code of Conduct & other minor things

### PR DESCRIPTION
**Pull request by bnvk**
Hey all. I made most of the changes that [were suggested](https://github.com/opensourcedesign/opensourcedesign.github.io/commit/1a382526ffddee41e7ced55ef33b4e11ab6bb42a) months ago. Sorry for dragging my feet on this!

I also updated a link to the CoC on the About page, as well as some other minor capitalization & word changes to the About page.

### CODE REVIEW

**Comment by simonv3** [comment]
We have Travis CI?

**Comment by simonv3** [comment]
So, the Travis CI failures are: 

* [ ] Link to COC doesn't exist (which makes sense because presumably this PR will create it)
* [ ] Link to emails doesn't exist?
* [ ] Ada Initiative their certificate has expired (change link to http?)
* [ ] Marked.js not found. #36.

**Comment by GarthDB** [comment]
I submitted a pull request with the Travis setup last night. Makes it easier to see if a pull request builds without having to pull and check it locally.

If you don't use the full domain name with internal links it will fix that issue with linking to new content (like the coc)

You can check the tests locally by running `rake test` so you can check if these things are fixed before pushing them up. You'll probably need to run `bundle install` first to get all the dependencies.

**Comment by simonv3** [comment]
@GarthDB awesome, thanks for doing that.

**Comment by GarthDB** [comment]
The email links should be fine if you use `mailto:` in front of them in the href.

**Comment by GarthDB** [comment]
That just leaves the `marked.js` file.

**Comment by bnvk** [comment]
@simonv3 oops. Spaced on that. Fixed the email addresses. Yes, the link to the CoC is in the pull request... weird that Travis CI doesn't take that into account. I actually just moved the entire `/slideshows` directory to [it's own repo](https://github.com/opensourcedesign/slideshows) as we should try to keep the main repo reasonably sized- just shrunk it from 15 -> 12MB with this change. Personally, I think leaving the Ada as https is fine- they'll prolly renew their cert and all will good!

@GarthDB thanks a lot for adding CI stuffs. That's rad!

**Comment by GarthDB** [comment]
Travis doesn't know about the domain name or where the page is going to be. It just builds the Jekyll site locally and checks the links.



—

**Pull request merged**
