### PR TITLE
Updates to projects

### PR DESCRIPTION
**Pull request by simison**
- https'ify some links
- Add Automattic.com
- Add Trustroots.org
- Update some links
- Change _"Open source projects with good design..."_  to _"Open source projects *and organisations* with good design"_ for better SEO.

### CODE REVIEW

**Comment by ei8fdb** [comment]
Thoughts @belenbarrospena @evalica? Could you maybe review also. 

It's a quick review. :)

**Comment by simison** [comment]
Also, a disclaimer that I'm associated with both Trustroots and Automattic but I genuinely think they're good examples of open source + design done right. 🙃

**Comment by jancborchardt** [comment]
Cool! Thank you @simison!

- Would it not make sense to replace BeWelcome with Trustroots as I assume development has stalled there? Or at least, the design of Trustroots is for sure much better.
- As Ubuntu and Canonical is combined, maybe it makes sense to combine Automattic and Wordpress?

**Comment by simison** [comment]
>Would it not make sense to replace BeWelcome with Trustroots as I assume development has stalled there? 

They're still active. Just they haven't published the new version that they've been working on for like a year or two: https://github.com/BeWelcome/rox/graphs/contributors

> Or at least, the design of Trustroots is for sure much better.

No comments from me on this. ;-)

If you feel like it doesn't fit in the list, let's leave it for another PR.

> As Ubuntu and Canonical is combined, maybe it makes sense to combine Automattic and Wordpress?

While Automattic contributes to .org version a lot and both org and com were founded by the same person, WordPress Foundation and  Automattic/WordPress.com are much more separate things than Ubuntu/Canonical or Mozilla org/inc. I wouldn't bundle them into the same line. [Read more](https://en.support.wordpress.com/com-vs-org/)

**Pull request merged**
