### PR TITLE
Introduced archive link of Open Design Foundation to goal page 

### PR DESCRIPTION
**Pull request by samrath-sudesh-acharya**

### CODE REVIEW

**Review by Erioldoesdesign — APPROVED** [review]
Looks good to me! :)

**Comment by Erioldoesdesign** [comment]
Alternatively, there is also the github repo for the open design foundation here: https://github.com/DesignOpen/designopen.github.io

we could include this too in the text?

**Comment by samrath-sudesh-acharya** [comment]
ok i could add this

**Comment by samrath-sudesh-acharya** [comment]
@Erioldoesdesign 
I added repo link. Tried to make it small but couldnt doing,but couldn't 😔 

``` diff
- You would also like to have a look at the Open Design Foundation, fine folks there are doing some awesome works, similar to our goals.Open Design Foundation website has gone down due some reason, but we have an archive of the site on our Wayback Machine.
+Open Design Foundation website has gone down due some reason, but we have an archive of the site on our Wayback Machine and checkout their [Github repository](https://github.com/DesignOpen/designopen.github.io).
```

**Review by Erioldoesdesign — APPROVED** [review]
I think this is all good :)

**Comment by samrath-sudesh-acharya** [comment]
OK

**Review by Erioldoesdesign — APPROVED** [review]
LGTM

**Review by SaptakS — APPROVED** [review]

**Pull request merged**
