### PR TITLE
Close #141. Change about to goals until we have an about page

### LINKED ISSUE #141: "our goals" links to a 404 (/about/) from homepage
If you click "our goals" at http://opensourcedesign.net you get a 404 at http://opensourcedesign.net/about/

### PR DESCRIPTION
**Pull request by simonv3**

### CODE REVIEW

**Comment by bnvk** [comment]
Sorry. Already fixed this. I really don't think things this tiny need pull-requests from the core web team like us... it just slows things down and makes project hard.

**Comment by jancborchardt** [comment]
@bnvk if it would have been in a pull request, it would have been visible that it was already done. ;)

**Comment by simonv3** [comment]
What if we did middle of the road where if it's a small thing you do a PR and merge it if it's minor?

**Comment by simonv3** [comment]
That way people get notified of the fix, but you still get to move on.

**Comment by jancborchardt** [comment]
@simonv3 that's what I mentioned at the Summit, am in favor. :)

**Pull request closed without merging**
