### PR TITLE
Updated with READMe with New Instructions

### PR DESCRIPTION
**Pull request by subz3r0o0**
This pull request updates the README file to improve the setup instructions for new contributors to the Open Source Design website. The updates include:

- Detailed steps for managing Ruby versions using rbenv, aimed at helping new contributors set up their development environments more efficiently.
- An expanded prerequisites section that provides step-by-step guidance on installing necessary tools and dependencies. This aims to reduce setup time and potential configuration errors.
Additional context to help new contributors understand the importance of each step and how they fit into the overall development process.

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
Please remove .DS_Store

**Comment by subz3r0o0** [comment]
did it work?

**Review by Erioldoesdesign — CHANGES_REQUESTED** [review]
Looks good except being clear about the website url :))))

**Comment by subz3r0o0** [comment]
done!

**Review by subz3r0o0 — COMMENTED** [review]
Added link to osd site.

**Review by Erioldoesdesign — APPROVED** [review]
LGTM!

**Comment by Arhell** [comment]
@subz3r0o0  unfortunately there is this file that I wrote about above. Sync with the main branch, I added exceptions https://github.com/opensourcedesign/opensourcedesign.github.io/pull/450

It should help.

**Comment by subz3r0o0** [comment]
did it work?

**Comment by Arhell** [comment]
https://github.com/opensourcedesign/opensourcedesign.github.io/pull/447/files
image folder
I think that since it is already in the history of the git, it needs to be done manually.

**Comment by Erioldoesdesign** [comment]
> sorry just to clarify. what file do i need to remove manually? the ds file ?

You can delete after the merge :)

**Comment by Erioldoesdesign** [comment]
> sorry just to clarify. what file do i need to remove manually? the ds file ?

Also you can delete from the link that arhell gave
Screenshot 2024-06-09 at 18 35 30

**Review by Arhell — APPROVED** [review]

**Pull request merged**
