### PR TITLE
adds Github activity feed to homepage

### PR DESCRIPTION
**Pull request by bnvk**
Here's a screenshot of how this looks:

screen shot 2015-05-16 at 4 28 32 pm

It's rough in that is has some silly comment for the feed and does not link to the individual items, but it's a start. What do you think @jancborchardt @simonv3 @danilapellicani etc... :)

### CODE REVIEW

**Comment by simonv3** [comment]
:+1: looks good to me.

I think it'll liven up the front page a bit. Maybe as we get more content we can move things around and de-emphasize it.

**Comment by jancborchardt** [comment]
Great stuff! I’m not sure we should emphasize it that much already though. Maybe it would be better to do another section below the »Projects« with one column being the Github activity feed and the other column being the Twitter feed.

(I don’t wanna artificially postpone this by asking for another feature in the form of a Twitter feed. But I would say we should _not_ de-emphasize the projects with a technical feed like that. And giving it a full or half column below that would look strange layout-wise. :)

**Comment by bnvk** [comment]
@jancborchardt I don't follow / understand your suggestion in the last paragraph. I do agree, this is not an ideal design, but overall, I think our site is not in an "ideal" state but rather in an iterative building block state- we have LOTS more to add to the homepage including overall proper branding design work. This is just one component I think should exist and be iterated upon.

**Comment by simonv3** [comment]
@jancborchardt @bnvk I don't think merging this in can hurt, since we'll be designing visual soon.

*But* maybe it's time to do some sketches of what we want different parts of the site / architecture to look like? @ScintillaLuz has offered to help with visual when she has time starting the 21st, so maybe before that time we can get some rough wireframes together for her? I can take the lead on that but it would be great if we could get some other people more involved this way.

With concept wireframes we can also just architect the site into a new direction, get some ideas on paper, etc. I think it might be a *really* helpful step.

**Comment by bnvk** [comment]
@jancborchardt yah, that's my thinking- push this up as it works and adds tiny speck of value to current site... then iterate on it soon!

**Comment by jancborchardt** [comment]
Works for me then! :)

**Pull request merged**
