### PR TITLE
Update 2015-04-25-welcome-to-open-source-design.markdown

### PR DESCRIPTION
**Pull request by dominicrico**
updated all permal links to shorter urls as discussed in [events issue #26](https://github.com/opensourcedesign/events/issues/26)
also added a redirect of the old links to the new perma links

### CODE REVIEW

**Comment by dominicrico** [comment]
HTML Proofer is not able to check the new permalinks and therefore fails.

**Comment by simonv3** [comment]
Awesome, tested locally and they work - let's see on live!

**Comment by dominicrico** [comment]
Hopefully they are doing live the same job as local :D

**Comment by dominicrico** [comment]
Oh, we have to enable it in the config too! So that the redirects work.
```
gems:
  - jekyll-redirect-from
```

**Pull request merged**
