### PR TITLE
Site Redesign

### PR DESCRIPTION
**Pull request by simonv3**
Based on the conversation in #17 I've made some changes to the front page and the articles. This is a pretty big re-write, so please try and pull the code down and run it on your own computer before giving it the OK. 

Edit based on feedback:

screenshot 2015-11-24 19 55 16

Things I have no idea that work: (because of Cross Origin Request policies) whether the events get loaded or the jobs get loaded. This is pretty minor though.

This should close #42.

### CODE REVIEW

**Comment by Volker-E** [comment]
A useful website above-the-fold starts with attractive content and not with just a logo. UX horror. I have to say, I doubt this being an improvement.

**Comment by GarthDB** [comment]
I kinda have to agree with @volker. This is a content based site. A large header is fine for an advertising micro site that needs to grab attention, but even then it uses large relevant imagery or video. This seems to just be keeping readers from content.

**Comment by simonv3** [comment]
@Volker-E and @GarthDB that's fair. There's no real reason why the logo should take up so much space. Have you had a look at the site itself and not just at the screenshot I posted? It'd be great to get some feedback on those parts as well.

**Comment by simonv3** [comment]
@Volker-E @GarthDB just pushed some changes. 

screenshot 2015-11-24 18 46 59

(reflected in PR as well).

**Comment by bnvk** [comment]
@simonv3 great job putting in the work and getting us closer to the goal. Huge thanks man. It's starting to look like a nicely designed site by and for designers :)

I pulled in the changes. I get the criticism above, but I rather liked a nice minimal start. Here's some feedback:

- Try making the name an interval larger
- Add our tagline "bringing great design to open source software" under the title in lighter gray
- Those paragraphs might fit nicely side by side 
- Upon scrolling down (when navbar goes black) seems like the name should show up in navbar

I'll check more tomorrow. It's getting late here ;)

**Comment by GarthDB** [comment]
I'm just on my phone right now.




I would recommend the text not be centered, rather make it aligned left and center the block. Adjust the width to make a nice rag.



—

**Comment by simonv3** [comment]
@GarthDB That's what that looks like 

screenshot 2015-11-24 19 57 49

**Comment by GarthDB** [comment]
Better!

**Comment by bnvk** [comment]
@simonv3 great stuff! You rock, tons!

**Pull request merged**
