### PR TITLE
[Work in progress] Add affiliation part to front page

### PR DESCRIPTION
**Pull request by jancborchardt**
Added the logos as a starting step for **Missing Affiliation page on the website #168** :) (They are already minified via scour.)

@aaqaishtyaq we should put them on the frontpage on the bottom so they are present, but not in the footer so they are not on all pages. Sounds good?

Also we should link the logos to their websites, what do you think @opensourcedesign/website

### CODE REVIEW

**Comment by jancborchardt** [comment]
And just to specifiy @RDIL cause you added the tag to the issue: This would not be a new page, but on the bottom of the front page.

We should not create new pages, but we are rather about to reduce the pages, as specified in the website discussion at https://discourse.opensourcedesign.net/t/open-source-design-website-review/773 :slightly_smiling_face:

**Comment by RDIL** [comment]
Ah okay

**Comment by jancborchardt** [comment]
@AnXh3L0 this is the pull request with the assets. :)

The code for the Open Collective embed seems to be this:

```
// Not sure if this JS file is needed?
<script src="https://opencollective.com/opensourcedesign/banner.js"></script>

// Sponsors
<object type="image/svg+xml" data="https://opencollective.com/opensourcedesign/tiers/sponsor.svg?avatarHeight=36&width=600"></object>

// Backers
<object type="image/svg+xml" data="https://opencollective.com/opensourcedesign/tiers/backer.svg?avatarHeight=36&width=600"></object>

// One-time sponsor
<object type="image/svg+xml" data="https://opencollective.com/opensourcedesign/tiers/one-time-sponsor.svg?avatarHeight=36&width=600"></object>
```

**Comment by AnXh3L0** [comment]
At the moment, I have added two new sections for Supporters and Affiliates, need some ideas/thoughts on how to improve it visually.

image

**Comment by evalica** [comment]
We could also separate the OpenCollective backers in a different category. So that would mean 3 categories: Affiliates, Supporters and Backers. 

Also I would have the Affiliates at the top, since they are well known, plus fewer than the Backers, that the list could increase.

**Comment by jancborchardt** [comment]
@AnXh3L0 the only feedback to improve it visually is to increase the whitespace above the Open Collective row a bit, as well as the whitespace above the "Affiliates" text. Then it looks great! :)

@evalica I actually would say the sorting is good:
- Supporters on top, since they did significant monetary support
- Backers inside of supporters since it’s also monetary support
- Affiliates on the bottom since it’s "just" affiliation. I would say the Supporters are actually more well-known than the affiliates we have at the moment.

**Comment by elioqoshi** [comment]
Since this is approved, let's go ahead and merge this. We can revisit the sorting in the new website redesign:
https://github.com/opensourcedesign/opensourcedesign.github.io/issues/242

**Comment by AnXh3L0** [comment]
@elioqoshi the changes I made weren't in this branch yet, that's why they aren't online.

**Comment by elioqoshi** [comment]
Ah okay sorry I was not aware. Ping us when they are

**Comment by jancborchardt** [comment]
@AnXh3L0 can you do a pull request with your changes then? I can do the additional adjustments too. :)

**Comment by AnXh3L0** [comment]
Yes, I can do a PR by the end of this week.

**Comment by jancborchardt** [comment]
@AnXh3L0 when you do a PR, I just remembered we should also add the Open Source Initiative to the affiliates! :) This would be the page to link to: https://opensource.org/affiliates

**Pull request merged**
