### PR TITLE
Add Elementary OS to the project list

### PR DESCRIPTION
**Pull request by alyakimenko**
This seeks to add [Elementary OS](https://elementary.io/en/) to the [project list](https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/projects.md).

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by Erioldoesdesign** [comment]
@alyakimenko is this an oss project? I can't find the OSS details

**Comment by alyakimenko** [comment]
@Erioldoesdesign they do [a lot of open-source](https://github.com/elementary).

**Comment by Erioldoesdesign** [comment]
> @Erioldoesdesign they do [a lot of open-source](https://github.com/elementary).

Awesome! looks very cool. The PR would need a link specifically to how design is done in the projects, like a blog or guide or design comms channel etc. Any idea if those are maintained by the team?

**Comment by alyakimenko** [comment]
@Erioldoesdesign I truly believe that the [Human Interface Guidelines](https://docs.elementary.io/hig) is the most comprehensive guide they use across their projects. And as for a blog, there're [design-related blog posts](https://blog.elementary.io/tags/#design) on the official website.

But I've already added links to these materials in the PR. Do you think they are not enough?

**Comment by Erioldoesdesign** [comment]
> @Erioldoesdesign I truly believe that the [Human Interface Guidelines](https://docs.elementary.io/hig) is the most comprehensive guide they use across their projects. And as for a blog, there're [design-related blog posts](https://blog.elementary.io/tags/#design) on the official website.
> 
> But I've already added links to these materials in the PR. Do you think they are not enough?

Ah i'm so sorry! I do agree those are sufficient. In my clicking around checking to see what the project was I neglected to check the PR details again. looks fine to me :)

**Review by Erioldoesdesign — APPROVED** [review]
LGTM

**Pull request merged**
