### PR TITLE
Tried to fix the Gemfile

### PR DESCRIPTION
**Pull request by RDIL**
This gem is missing, so maybe it will mitigate the issue

### CODE REVIEW

**Comment by jancborchardt** [comment]
What is that actually used for, and how can I reproduce the error for testing? (Or how does the error look like?)

**Comment by jancborchardt** [comment]
Ah or is this about #224?
In this case @thesanjeevsharma @NirmalKumarJoshi could you also check if this fixes it for you? :)

**Comment by RDIL** [comment]
Yes this is from that issue - it adds the time zone info gem which nokogiri has trouble sometimes without it.

**Comment by jancborchardt** [comment]
Sorry for the lateness here @RDIL, it’s now in. :)

**Pull request merged**
