### PR TITLE
Add link Section 

### PR DESCRIPTION
**Pull request by aryasoni98**
#284
I just add the link in **Support** , **Conferences**, **Affiliates** section

### CODE REVIEW

**Comment by SaptakS** [comment]
@aryasoni98 you will need to rebase this PR so that all the previous commit by other people are not repeated while merging. Also is #328 no longer valid and can be closed then? I think both these PRs address the same issue. If so, do close the PR. Let me know if you need any assistance!! :)

**Comment by aryasoni98** [comment]
@SaptakS  Please review my PR

**Review by SaptakS — CHANGES_REQUESTED** [review]
Hi. As I can see, none of the anchor tags have a closing tag. All anchor tags need to have a closing `</a>`. Please add a closing anchor tag as needed everywhere.

**Comment by Erioldoesdesign** [comment]
> Hi. As I can see, none of the anchor tags have a closing tag. All anchor tags need to have a closing `</a>`. Please add a closing anchor tag as needed everywhere.

@aryasoni98 did you see Saptak's request above?

**Comment by Erioldoesdesign** [comment]
@SaptakS and @aryasoni98 I'm thinking of closing this if the author doesn't edit by end of 2022?

**Pull request closed without merging**
