### PR TITLE
Update logo to square version to comply with OSI trademark (and remove outdated logos to avoid confusion)

### PR DESCRIPTION
**Pull request by jancborchardt**
Wasn’t able to fully test it, please check everyone. cc @bnvk @simonv3 @massonpj @evalica @grahamperrin @jdittrich @belenbarrospena :)

This is to comply with OSI guidelines as per https://github.com/opensourcedesign/events/issues/43#issuecomment-283807989, and using the square logo as proposed in https://github.com/opensourcedesign/organization/issues/68#issuecomment-293296056
I already changed it on https://twitter.com/opensrcdesign and https://github.com/opensourcedesign, the forum at https://discourse.opensourcedesign.net/ uses the square logo too.

(Also, it would be great if the images related to the search-article could be moved to a subfolder so we only have the logos in the root images folder.)

### CODE REVIEW

**Comment by jancborchardt** [comment]
@jdittrich for critical stuff like this in the future let’s ideally have some more people than one review it. :)

**Comment by evalica** [comment]
Missing from the Website: 
1. the SVG in h1.brand-heading 
brand-heading

2. .navbar-brand.page-scroll > .logo SVG
screen shot 2017-04-13 at 18 02 14

**Comment by jancborchardt** [comment]
Yeah, it seems the opensourcedesign-logo.svg is linked for the frontpage at https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/index.html#L11 and the header at https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/_includes/header.html#L9

And on the page it gets included. Is anything required to build the page, or should it not be automatic after a push? cc @bnvk @simonv3 I assumed this doesn’t need any building because also the favicon and other things seem to work fine.

**Comment by simonv3** [comment]
I think for some reason it's organized in an includes? It's referencing this file: https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/_includes/img/opensourcedesign-logo.svg

I can pull it down now and try to fix it, should fairly straightforward (famous last words).

**Comment by simonv3** [comment]
PR here: https://github.com/opensourcedesign/opensourcedesign.github.io/pull/93

**Pull request merged**
