### PR TITLE
added events blurb to homepage and links

### PR DESCRIPTION
**Pull request by bnvk**

### CODE REVIEW

**Comment by jancborchardt** [comment]
Can we move the fork to the @opensourcedesigners org?

**Comment by simonv3** [comment]
@jancborchardt I'm not sure what you mean?

**Comment by bnvk** [comment]
@jancborchardt I think you mean "move my fork of the Shout project to the OSD github repo instead of my personal one, yes?" Yes, I plan to do that once I finish the actual theme and it's abstracted to be a "Shout theme" not a fork of Shout itself, then I was planning on moving it. If ti's important to you, I can do it sooner- I just already gave people access / created issues / etc... cc: @simonv3

**Comment by simonv3** [comment]
gotcha!

**Comment by jancborchardt** [comment]
Yeah, it would be cool to have it on our org if we say »Help work on _our_ fork«. :) There’s no downside in moving it earlier.

**Comment by bnvk** [comment]
@jancborchardt updated this and it now points to [Slick](https://github.com/opensourcedesign/slick) repo!

**Comment by jancborchardt** [comment]
@bnvk hehe, great name :D

**Pull request merged**
