### PR TITLE
Summit Website

### PR DESCRIPTION
**Pull request by simonv3**
screenshot 2017-05-04 18 39 40

### CODE REVIEW

**Comment by evalica** [comment]
How will we link the Summir page from the Homepage? Maybe an entry in the Menu? Other ideas?

**Comment by evalica** [comment]
How will we link the Summir page from the Homepage? Maybe an entry in the Menu? Other ideas?

**Comment by simonv3** [comment]
Yeah, we can add it to the menu and also create an event for it?

**Comment by elioqoshi** [comment]
Yeah menu and event sounds good to me

**Comment by bnvk** [comment]
@simonv3 nice work. Merging!

**Comment by simonv3** [comment]
Let's tweet about it too!

**Pull request merged**
