### PR TITLE
image optmizations and css compressed

### PR DESCRIPTION
**Pull request by GarthDB**
Did a few things:
- Compressed svgs
- Switched main logo to svg, reduced ~100b and is responsive for hidpi
- Used inline svg with jekyll include. Reduces requests, also allows for color variation in the header logo with a single file.
- Compressed CSS (sass output)

### CODE REVIEW

**Comment by GarthDB** [comment]
Tests fixed. Ready to be reviewed and pulled.

**Comment by jancborchardt** [comment]
Didn’t test yet, but looking through the code and improvements it looks good! Also good on removing the superfluous alt text. :+1:

**Comment by simonv3** [comment]
Looks good!

**Comment by Volker-E** [comment]
Great change!

**Pull request merged**
