### PR TITLE
Use local fonts rather than google CDN

### PR DESCRIPTION
**Pull request by Jc-L**

### CODE REVIEW

**Comment by jancborchardt** [comment]
@Jc-L thank you for the contribution! :) 

We should actually even not rely on Google for the font delivery. We already have them in the fonts folder at https://github.com/opensourcedesign/opensourcedesign.github.io/tree/master/fonts – do you mind adjusting the pull request to load the fonts from that folder instead? :)

**Comment by Jc-L** [comment]
@jancborchardt & @RDIL : pull request updated

**Comment by RDIL** [comment]
I’ve updated the PR title so it is more accurate.

**Comment by jancborchardt** [comment]
@elioqoshi yeah, I guess it’s not needed to include the Vietnamese character set. Wanna remove it?

**Pull request merged**
